[package]
name = "gpu-idle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
nvml-wrapper = "0.9.0"
nvml-wrapper-sys = "0.7.0"
sysinfo = "0.30.3"
